image: docker:latest
services:
  - name: docker:dind
    alias: static-webapp

stages:
  - Build
  - Test acceptation
  - Release image
  - Deploy review 
  - Stop review 

docker-build:
  stage: Build
  #tags:
  #  - carlinfg
  script:
    - docker build --pull -t staticapp .
    - docker save staticapp > staticapp.tar
  artifacts:
    paths:
      - staticapp.tar


test-acceptation:
  stage: Test acceptation
  script:
    - docker rmi -f staticapp >/dev/null 2>&1 && echo "Image précédente supprimé." || echo "Aucune image du même nom n'exite."
    - docker load < staticapp.tar
    - docker rm -f staticapp-test >/dev/null 2>&1 && echo "Conteneur précédent supprimé." || echo "Aucun conteneur du même nom n'exite."
    - docker run --rm -d -p 80:80 --name staticapp-test staticapp:latest
    - sleep 5
    - apk --no-cache add curl
    - ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' staticapp-test)
    - curl -I "http://static-webapp"
    #- curl "http://$ip_address" grep -i "dimentions" #information du head
    - echo "Adresse IP du conteneur  $ip_address"
    - docker rm -vf staticapp-test && echo "clean container"



release-image:
  stage: Release image
  script: 
    - docker load < staticapp.tar
    #ajout des variable d'environnement permettant de tagger la release
    - docker tag staticapp "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag staticapp "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    #configuration de login au registry gitlab
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"


deploy-review:
  stage: Deploy review
  only:
    - merge_requests
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: ${REVIEW_LINK}
    on_stop: stop-review
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - APP_NAME=staticapp-$CI_COMMIT_REF_NAME
    - "[[ ${#APP_NAME} -gt 31 ]] && echo 'the name of the heroku application you want to create is longer than 30 characters' && exit 1"
    - heroku create $APP_NAME || echo "project already exist"
    - heroku container:push -a $APP_NAME web
    - heroku container:release -a $APP_NAME web


stop-review:
  stage: Stop review
  variables:
    GIT_STRATEGY: none
  only:
    - merge_requests
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop #ajout de l'action stop pour la supp de l'environnement review
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku apps:destroy -a staticapp-$CI_COMMIT_REF_NAME --confirm staticapp-$CI_COMMIT_REF_NAME