image: docker:latest

services:
  - name: docker:dind
    alias: docker-vm    

stages:
  - build
  - test-acceptation

before_script:
  - docker info

docker-build:
  stage: build
  script:
    - docker build -t staticapp .
    - docker save staticapp > staticapp.tar
  artifacts:
    paths:
      - staticapp.tar 

test-acceptation:
  stage: test-acceptation
  script:
    - docker info  # Vérifiez si le démon Docker est disponible
    - docker rmi -f staticapp 2>/dev/null || echo "Image déjà supprimée" 
    - docker load < staticapp.tar
    - docker rm -vf staticapp-test 2>/dev/null || echo "Conteneur déjà nettoyé"
    - docker run -d -p 80:80 -e PORT=80 --name staticapp-test staticapp
    - sleep 5
    - apt install -y curl
    - curl "http://docker-vm" | grep "Welcome"
    - docker rm -vf staticapp-test && echo "Conteneur nettoyé"
