image: docker:latest
services:
  - name: docker:dind
    alias: docker-vm    

stages:
  - Build
  - Test acceptation

docker-build:
  stage: Build
  script:
    - docker build -t staticapp .
    - docker save staticapp > staticapp.tar
  artifacts:
    paths:
      - staticapp.tar 

test acceptation:
  stage: Test acceptation
  script:
    - docker rmi -f staticapp || echo "image already deleted" 
    - docker load < staticapp.tar
    - docker rm -vf staticapp-test || echo "container already cleaned"
    - docker run -d -p 80:80 -e PORT=80 --name staticapp-test staticapp
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker-vm" | grep  "Hello world!"
    - docker rm -vf staticapp-test && echo "clean container"